### PR TITLE
`odgi tips`

### PR DESCRIPTION
**Pull request by subwaystation**
This brings in `odgi tips`: Identifying break point positions relative to given query (reference) path(s) of all the tips in the graph or of tips of given path(s).

Tasks to complete this PR:

- [x] Walk the tips from the back of the paths.
- [x] `bed_writer_thread.hpp`: This will allow us to write faster to a file. Will be similar to or even abstract https://raw.githubusercontent.com/pangenome/odgi/446c58ee3fd48401c18e45b3a77f7293dd0a8b35/src/algorithms/bed_records.hpp.
- [x] Allow the input of a list of query paths by FILE.
- [x] Allow the input of a list of target paths by FILE.
- [x] Add progress bar while traversing the target paths.
- [x] Add progress bar for building the `step_position_index`.
- [x] Add Documentation. Especially explaining the additional, optional BED columns.
- [x] Clean up the code and put most of it into `algorithms/tips.c*`
- [x]  We should be able to write the target path(s) that do not hit the query path(s) into an extra file. Tab-delimited. 1st col query path. 2nd col target path. We might need another writer thread then.
- [x] Add another column to the BED output: walking start direction (`1` for`front` or `0` for `back`).
- [x] Parallelize the `step_index` construction. 
- [x] Be more precise when selecting the reference range. Only pick the Nth possible ranges! Maybe add a Jaccard limit, too.
- [x] Detailed Documentation.
- [x] Code documentation.
- [x] Performance power up!

### CODE REVIEW

**Comment by subwaystation** [comment]
Applying this to the `LPA.gfa` in the `test` folder.

``` bash
odgi tips -i LPA.gfa.og -q chm13__LPA__tig00000001 -t 12 -v LPA.gfa.og.tips.no_hits.tsv > LPA.gfa.og.tips.bed
bedtools sort -i LPA.gfa.og.tips.bed > LPA.gfa.og.tips.bed.sorted.bed
bedtools merge -c 4,5,6,7 -o collapse -i LPA.gfa.og.tips.bed.sorted.bed -d 10000 > LPA.gfa.og.tips.bed.sorted.bed.10k.bed
```
We only see 3 ranges on our 10k window:

```
chm13__LPA__tig00000001	0	10347	0.00000000000000000,0.00000000000000000,5045.00000000000000000,5586.00000000000000000,5827.00000000000000000,5827.00000000000000000,6550.00000000000000000,7430.00000000000000000,9096.00000000000000000,9884.00000000000000000,10346.00000000000000000	HG02572__LPA__tig00000001,HG02572__LPA__tig00000005,HG002__LPA__tig00000005,HG002__LPA__tig00000001,HG00733__LPA__tig00000001,HG01358__LPA__tig00000010,HG01358__LPA__tig00000002,NA19239__LPA__tig00000006,NA19240__LPA__tig00000012,NA19239__LPA__tig00000002,NA19240__LPA__tig00000001	38,3,0,0,0,0,0,0,0,0,0	1,1,1,1,1,1,1,1,1,1,1
chm13__LPA__tig00000001	47024	47025	47024.00000000000000000	HG00733__LPA__tig00000008	0	1
chm13__LPA__tig00000001	322638	329929	322638.00000000000000000,324844.00000000000000000,324849.00000000000000000,325218.00000000000000000,325235.00000000000000000,326498.00000000000000000,327613.00000000000000000,328356.00000000000000000,329822.00000000000000000,329822.00000000000000000,329823.00000000000000000,329928.00000000000000000	NA19239__LPA__tig00000006,NA19240__LPA__tig00000001,HG00733__LPA__tig00000001,HG00733__LPA__tig00000008,NA19240__LPA__tig00000012,HG02572__LPA__tig00000001,HG01358__LPA__tig00000002,HG02572__LPA__tig00000005,HG002__LPA__tig00000001,HG01358__LPA__tig00000010,HG002__LPA__tig00000005,NA19239__LPA__tig00000002	236954,285141,295823,283663,260077,309177,337243,311314,329346,240281,274123,263970	0,0,0,0,0,0,0,0,0,0,0,0
```

Let's visually validate them with `odgi viz`.

``` bash
odgi viz -i LPA.gfa.og -r chm13__LPA__tig00000001:0-10400 -o LPA.gfa.og.0-10400.png -bm
```
LPA gfa og 0-10400

``` bash
odgi viz -i LPA.gfa.og -r chm13__LPA__tig00000001:47000-47100 -o LPA.gfa.og.47000-47100.png -bm
```
LPA gfa og 47000-47100

``` bash
odgi viz -i LPA.gfa.og -r chm13__LPA__tig00000001:322600-330000 -o LPA.gfa.og.322600-330000.png -bm
```
LPA gfa og 322600-330000

`odgi tips` works! :)

**Comment by subwaystation** [comment]
Current results: https://docs.google.com/presentation/d/1UWKiFyF_IDt3YEhUgSxAKhhLfvCK95ietYDYo5h9VtM/edit#slide=id.p.
`odgi tips` is still too slow. Ideally, it will become 10x faster. But 2x is the minimum I will aim for.

**Comment by subwaystation** [comment]
The last commit brings the wall clock time for the chr8 hprc pggb graph down from 17:15 to 13:43 on my laptop.
This may not seem much, but each time we run `odgi tips`, ~6 minutes are spend to build the step index.
So effectively, we are at a ~1.5x speedup. 
I have some more ideas, hoping we can reach 2x. With my current mind, though, a 10x speedup is not possible.

**Comment by AndreaGuarracino** [comment]
image

**Comment by subwaystation** [comment]
For all chromosomes of the new HPRC PGGB RC1 graph `odgi tips` indulges in 3 hours of wall time clock. Given that building the step indices take ~50% of that time, this is fine for now.

**Pull request merged**
