### PR TITLE
Python objects should implement  hash and equals methods.

### PR DESCRIPTION
**Pull request by JervenBolleman**
Also make step and edge information easier to access.

### CODE REVIEW

**Comment by ekg** [comment]
Should this be merged?

**Comment by JervenBolleman** [comment]
The hash and equals code part yes. The other. Part is nice to have. Do double check that it still applies, it's been a while since I opened the pull request.

**Comment by JervenBolleman** [comment]
Yeah this is actually important and breaks lot's of usecases and simple things like sets in python

**Comment by ekg** [comment]
I'll close this as it's gone stale. Reopen if we should pick this back up.

**Pull request closed without merging**
