### PR TITLE
`odgi flip` fixed path metadata corruption and optimization

### PR DESCRIPTION
**Pull request by AndreaGuarracino**

### CODE REVIEW

**Comment by cgroza** [comment]
Are we sure this issue is fixed.
odgi flip is corrupting my paths.

Odgi version:
```
[cgroza@nc30139 tmp]$ odgi
odgi: optimized dynamic genome/graph implementation, version v0.7.3 "Fissaggio"
```

For example before flipping:

```
[cgroza@nc30139 tmp]$ odgi paths -i hg38#chr12_KRT.bed.inject.og -L | tail
NA21309#2#JAHEPB010000010.1:12114062-12174403
UNMC-000003-01#hap1#h1tg000003l:12100591-12160945
UNMC-000003-01#hap2#h2tg000010l:77568868-77628933
UNMC-000004-01#hap1#h1tg000267l:2044073-2104140
UNMC-000004-01#hap2#h2tg000105l:1787173-1847534
UNMC-000004-04#hap1#h1tg000170l:17420408-17480473
UNMC-000004-04#hap2#h2tg000004l:51139607-51199968
Homo_sapiens.GRCh38#hap1#chr12:52249203-52309267
KRT86
KRT81
```

After flipping:
```
[cgroza@nc30139 tmp]$ odgi paths -i hg38#chr12_KRT.bed.inject.flip.og -L | tail
`
`
`
`
`
`
`
`
`
`
```
Other truncated path names:
```
UNMC-000004-04#hap2#h2tg000004l:51139607-51199968
UNMC-00
UNMC-00
UNMC-00
UNMC-00
UNMC-00
UNMC-00
UNMC-00
UNMC-00
UNMC-00
```

**Comment by AndreaGuarracino** [comment]
If you can share the input graph, I can take a look at it. However, #436 solved the problem completely, with the price of doubling the memory usage of `odgi flip`.

**Comment by cgroza** [comment]
Here is the input graph.
Is that commit included in the version I used, or I have to pull and recompile?

[hg38#chr12_KRT.bed.inject.og.gz](https://github.com/pangenome/odgi/files/9426714/hg38.chr12_KRT.bed.inject.og.gz)

**Comment by cgroza** [comment]
I pulled the latest code and the issue is solved. Thank you!

**Pull request merged**
