### PR TITLE
switch from Travis to github workflows

### PR DESCRIPTION
**Pull request by subwaystation**

### CODE REVIEW

**Comment by subwaystation** [comment]
This is annoying. @ekg Do you have any ideas why ASan is not happy with us?

**Comment by AndreaGuarracino** [comment]
image

**Comment by subwaystation** [comment]
The python tests fails because there is a problem with linking to `jemalloc`..... https://gitter.im/jemalloc/jemalloc?at=602a62a49ba13e72e42f0ba5

**Comment by subwaystation** [comment]
I decided to go for the hotfix as mentioned in https://github.com/AcademySoftwareFoundation/openvdb/issues/732#issuecomment-806553235

**Pull request merged**
